name: modernloginpage
description: A modern car rental application with animated login and signup pages.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/social/
    - assets/images/social/instagram.png
    - assets/images/social/facebook.png
    - assets/images/social/google.png
    - assets/images/car front 1.jpeg
    - assets/images/Car 4.jpeg
    - assets/images/bmw.png
    - assets/images/Mercedes.jpg
    - assets/images/tesla.png
    - assets/images/Toyota.png
    - assets/images/hyundai_verna.png
    - assets/images/bmw_3series.png
    - assets/images/toyota_camry.png

